### ISSUE TITLE
Timeout J2534 on Mazda MX-5 NC

### ISSUE THREAD

**Issue by matthijsvrenswoude** [speepsio/romdrop#3]
Hi Speepsio,

I want to Flash my ecu on my Mazda MX-5 NC 2.0 S-VT Touring from 2009. However, everytime I execute a command on my laptop connected to my car with Tactix openport 2.0 it results in an j2534 Timout. I was wondering if you could help me? I already tried switching usb cables and I am currently out of luck. To my mind it looks like an software issue... I do have to mention that the Tactrix openport is not the original made by tactrix but in my opinion that shouldn't be a problem.

Ill look forward to your response.

![ECU-Picture](https://user-images.githubusercontent.com/21951789/88046607-9c666580-cb50-11ea-9f73-f01014ece4e0.jpg)
(https://www.aliexpress.com/item/4000370301347.html?spm=a2g0s.9042311.0.0.7f944c4dNBV3zZ)

**Comment by shifty35** [comment]
It can be a little bit tricky to get it working on occasion.  My usual sequence is this:

Connect Tactrix to PC.  Wait for device to be recognized.
Start Romdrop.  Verify device is found.
Plug Tactrix into OBD2 port.  Turn on car.
Wait 20-30 and attempt to flash.

The Tactrix has different modes depending on if it gets power from the USB side (reflashing) or from the OBD2 port side (logging).

If this doesn't work, I suggest you buy a genuine Tactrix and try again.

**Comment by speepsio** [comment]
I use the same procedure as shifty35. Overall, I haven't had any feedback from others concerning timeouts. Was the issue resolved? and sorry for the insanely delayed response... I intend to start using Github for it's intended purpose, particularly tracking issues. ;)
