### ISSUE TITLE
Calibration IDs

### ISSUE THREAD

**Issue by shr3k** [speepsio/romdrop#4]
https://github.com/speepsio/romdrop/wiki/Calibration-IDs
L831 - MY2005 Euro 1.8 93 kW 5speed https://www.autoweek.nl/auto/38375/mazda-mx-5-18-exclusive/
L862 - MY2008 Euro 1.8 93 kW 5speed https://www.autoweek.nl/auto/54887/mazda-mx-5-18-ts/

**Comment by speepsio** [comment]
Sorry for the huge delay. Thanks for the info!
