### ISSUE TITLE
Track Patch Versions

### ISSUE THREAD

**Issue by shifty35** [speepsio/romdrop#8]
Presently, patches and definitions are unversioned, which makes tracking things challenging.  If you have a patched ROM, there is no way to tell which patch was applied, or which definition file should be used to modify it.

Potential solution: Reserve a few bytes somewhere in the patched ROM for the patch version.  For each new romdrop-patches release, the tag should be the same as the version string that winds up in the rom, ie "1.0.0" etc.  Also, the same tag should be applied to the version of romdrop that contains the associated definition file.

**Comment by speepsio** [comment]
Will sync patch, definition, and romdrop versioning from this point forward.
